version: "3.9" 

services:
  app:
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data: